languageCode = 'en-us'
title = 'Tracker'
enableGitInfo = true

[frontmatter]
  lastmod = ['lastmod', ':fileModTime', ':git', ':default']

[params]
  favicon = '/icons/icon.svg'

[taxonomies]
  artist = 'artists'
